<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="https://raw.githubusercontent.com/zznazzy/assn4/main/NationalParks"
           xmlns="https://raw.githubusercontent.com/zznazzy/assn4/main/NationalParks"
           elementFormDefault="qualified"
           attributeFormDefault="unqualified">
  <xs:element name="NationalParks">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="NationalPark" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Name" type="xs:string" />
              <xs:element name="Phone" type="xs:string" maxOccurs="unbounded" />
              <xs:element name="Address">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Number" type="xs:string" />
                    <xs:element name="Street" type="xs:string" />
                    <xs:element name="City" type="xs:string" />
                    <xs:element name="State" type="xs:string" />
                    <xs:element name="Zip" type="xs:string" />
                  </xs:sequence>
                  <xs:attribute name="NearestAirport" type="xs:string" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="Rating" type="xs:string" use="optional" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>
